# This tells Netlify where your functions are located.
# It should already be here.
[functions]
  directory = "netlify/functions/"

# This is the NEW, CRITICAL section that enables Netlify Blobs.
# This will fix the current error.
[build.processing.blobs]
  deploy_api = true

# This rule ensures your function URLs work correctly.
# It should also already be here.
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
